const { Router } = require('express')
const AuthController = Router()
const SignUpController = require('../controller/signup')
const LoginController = require('../controller/login')
const NewChatController = require('../controller/NewChat')
const PrivatRouterController = require('../controller/PrivateRoute')
AuthController.post('/signup', SignUpController.SingUp)
AuthController.post('/login', LoginController.Login)
AuthController.post('/new-user', NewChatController.NewChat)
AuthController.get('/privat-router', PrivatRouterController.PrivateRoute)
module.exports = AuthController